HardCodeWeb/Models/Category.cs
namespace HardCodeWeb.Models
{
    public class Category
    {
        public int Id { get; set; }

        public string? Name { get; set; }
        public string? Additional { get; set; } 
    }
}

HardCodeWeb/Models/Product.cs
namespace HardCodeWeb.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Count { get; set; }

        public string? AdditionalValues { get; set; }
        public int CategoryId { get; set; }
    }
}

HardCodeWeb/Controllers/CategoryController.cs
using HardCodeWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Security.Policy;
using System.Text;

namespace HardCodeWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly HttpClient _client;
        private readonly string _url = "https://localhost:7110/";
        public CategoryController() 
        {
            _client = new HttpClient();
        }

        public async Task<IActionResult> Index()
        {
            var response = await _client.GetAsync(_url + "api/Category/GetCategories");
            if (response.IsSuccessStatusCode)
            {
                return View(JsonConvert.DeserializeObject<IEnumerable<Category>>(await response.Content.ReadAsStringAsync()));
            }
            return NotFound();
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] Category? category)
        {
            if (ModelState.IsValid)
            {
                if (category != null)
                {
                    JObject val = JObject.Parse(JsonConvert.SerializeObject(category));
                    HttpContent content = new StringContent(val.ToString(), Encoding.UTF8, "application/json");
                    var response =  await _client.PostAsync(_url + "api/Category/AddNewCategory", content);
                    if(response.IsSuccessStatusCode)
                    {
                        return Redirect("Index");
                    }
                }
                return NotFound(category);
            }
            return NoContent();
        }
  
   
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (ModelState.IsValid)
            {
                if (id.HasValue && id.Value > 0)
                {
                    var response = await _client.GetAsync(_url + $"api/Category/DeleteCategory/{id}");
                    if (response.IsSuccessStatusCode)
                    {
                        return Redirect("Index");
                    }
                }
            }
            return NoContent();
        }
    }
}

HardCodeWeb/Controllers/ProductController.cs
using HardCodeWeb.Models;
using HardCodeWeb.Service.CategoryService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Text;

namespace HardCodeWeb.Controllers
{
    public class ProductController : Controller
    {
        private readonly HttpClient _client;
        private readonly string _url = "https://localhost:7110/";
        public ProductController()
        {
            _client = new HttpClient();
            _client.BaseAddress = new Uri(_url);
        }
        public async Task<IActionResult> Index()
        {
            var response = await _client.GetAsync("api/Product/GetProducts");
            var res = JsonConvert.DeserializeObject<IEnumerable<Product>>(await response.Content.ReadAsStringAsync());
            return View(res);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (ModelState.IsValid)
            {
                if(id.HasValue && id > 0)
                {
                    var val = await _client.GetAsync($"api/Product/GetProductById/{id}");
                    if(val != null)
                    {
                        return View(JsonConvert.DeserializeObject<Product>(await val.Content.ReadAsStringAsync()));
                    }
                    return BadRequest();
                }
                return NotFound(id);
            }
            return NoContent();
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            BaseCategoryService service = new BaseCategoryService(_client);
            return View(service.GetAllCategory().Result);
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] Product? product)
        {
            if(ModelState.IsValid)
            {
                if(product != null)
                {
                    JObject val = JObject.Parse(JsonConvert.SerializeObject(product));
                    HttpContent content = new StringContent(val.ToString(), Encoding.UTF8, "application/json");
                    var response = await _client.PostAsync("api/Product/AddNewProduct", content);
                    if(response.IsSuccessStatusCode)
                        return Redirect("Index");
                }
            }
            return NoContent();
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            if (ModelState.IsValid)
            {
                if(id.HasValue&&id.Value > 0)
                {
                    var response = _client.DeleteAsync($"api/DeletProduct/{id}");
                    if(response.IsCompleted)
                    {
                        return Redirect("Index");
                    }
                }
            }
            return View();
        }
    }
}

HardCodeWeb/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace HardCodeWeb.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

HardCodeWeb/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HardCodeWeb.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

HardCodeWeb/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HardCodeWeb.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

HardCodeWeb/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Orientation</h1> 
    @Html.ActionLink("ProductController","Index","Product") <br />
    @Html.ActionLink("CategoryController","Index","Category")
</div>

HardCodeWeb/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HardCodeWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HardCodeWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">HardCodeWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HardCodeWeb - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HardCodeWeb/Views/Category/Create.cshtml
@model HardCodeWeb.Models.Category

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
}

<h1>Create</h1>
@Html.
<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">  
        <form   method="post" asp-action="Category/Create"> 
       
  
                <div class="form-group">
                    <label  class="control-label"></label>
                    <input asp-for="Name" name="Name" class="form-control" placeholder="Name category"/>
                    <span class="text-danger"></span>
                </div>
        

                <div id="result" class="form-group">
                    <label class="control-label">Write attribute</label>
                    <input id="finish" name="Additional" asp-for="Additional" class="form-control" placeholder="color,weight..."/>
                    <span  class="text-danger"></span>
                </div>
           
            <div class="form-group">
                <input id="create" type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
 
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HardCodeWeb/Views/Category/Delete.cshtml
@model HardCodeWeb.Models.Category

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
 
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Additional)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Additional)
        </dd>
    </dl>
    
    <form method="post" asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HardCodeWeb/Views/Category/Index.cshtml
@model IEnumerable<HardCodeWeb.Models.Category>

@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<h1>Index</h1>

<p>
    @Html.ActionLink("Create New","Create");
</p>
<table class="table">
    <thead>
        <tr>  
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
      
      
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td> 
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

HardCodeWeb/Views/Product/Create.cshtml
@using HardCodeWeb.Models;
@model List<HardCodeWeb.Models.Category>

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
    Category selectedCategory = null ;
}
 
<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Product/Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
 
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input name="Name" placeholder="Name of product" asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input name="Description" placeholder="Description of product" asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Count" class="control-label"></label>
                <input name="Count" placeholder ="Count of product" asp-for="Count" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdditionalValues" class="control-label"></label>
                <input name="AdditionalValues" placeholder="AdditionalValues" id="AdditionalValues" asp-for="AdditionalValues" class="form-control" />
                <span asp-validation-for="AdditionalValues" class="text-danger"></span>
            </div>
            <div class="form-group">
                <select id="select1" onchange="handleSelectChange(event)" name="" class="user-select-all">
                    @foreach(var item in Model)
                    {
                        <option  class="options" value=@item.Id name="CategoryId" asp-for="CategoryId">@item.Name</option>
                    }
                </select> 
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
 

HardCodeWeb/Views/Product/Details.cshtml
@model HardCodeWeb.Models.Product

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Count)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Count)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalValues)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AdditionalValues)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
    </dl>
</div>
<div> 
    <a asp-action="Index">Back to List</a>
</div>

HardCodeWeb/Views/Product/Index.cshtml
@model IEnumerable<HardCodeWeb.Models.Product>

@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<h1>Index</h1>

<p>
    @Html.ActionLink("Create new ", "Create")
</p>
<table class="table">
    <thead>
        <tr>
        
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Count)
            </th>
 
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr> 
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Count)
            </td>
     
            <td> 
                @Html.ActionLink("Details", "Details", new {   id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>